### ISSUE TITLE
حل جاوااسکریپتی

### ISSUE THREAD

**Issue by AhmadMrf** [HamidMolareza/QueraProblems#28]
سلام
حل جاوااسکریپتی این سوال 👇
 https://quera.org/contest/assignments/50132/problems/171742
 رو لطف میکنید بذارید. من هرچقدر تلاش کردم ، خطا میده . در حالی که سوال هم واقعا سادس، 
احساس میکنم طریقه ورودی گرفتن یا خروجی دادن رو اشتباه میکنم. 
این جواب منه 
````
let num
  while (true) {
  num = +readline()
    if (!num) break
    let result = reverseSquare(num)
    console.log(result);
  }

function reverseSquare(n){
    const square = n ** 2
    let reverseNum = String(square)
    reverseNum = reverseNum.split('').reverse().join('')
    return reverseNum
}

````

**Comment by AhmadMrf** [comment]
اینجا میشه ارسال کرد. 
https://quera.org/problemset/171796/
دقیقا فکر میکنم مشکل همون ۰۰۴ باشه .
ولی من روش حل c++ رو که دیدم اون خروجی رو string میکنه ، ولی من که استرینگ میفرستم خطا میده که جواب درست نیست.

**Comment by HamidMolareza** [comment]
برنامه رو مستقیما با `V8` امتحان کردم. نحوه ورودی گرفتن مشکلی نداره. منطق برنامه هم مشکلی نداره!
مشکل توی ورودی بزرگ مثل `1000000001` هستش یا حتی کوچیکتر. خروجی باید `1000000002000000001` باشه ولی خروجی جاوااسکریپت `0000000002000000001` هستش.
این مشکل در زبانی مثل پایتون وجود نداره. ممکنه تیم کوئرا این نکته رو درنظر نگرفته باشن.

فعلا تنها راهی که به نظرم میرسه **پیاده‌سازی عمل ضرب** هستش! یعنی همونجور که خودمون توی کاغذ حساب می‌کنیم.
هدف این سوال چنین کاری نبوده ولی اگر تمایل داشته باشین و براتون جالب باشه می‌ةونید اینکار رو بکنید.

**Comment by HamidMolareza** [comment]
راستی اگر براتون سوال شد که چطوری با `V8` کار می‌کنم، جوابتون **داکر** و[ این مخزن](https://github.com/andreburgaud/docker-v8) هستش.
اگر با داکر آشنا هستین می‌تونید ازش استفاده کنید.

**Comment by HamidMolareza** [comment]
هرموقع لازم دونستین می‌تونید این ایشو رو دوباره باز کنید.
موفق باشید.

**Comment by HamidMolareza** [comment]
این نکته رو هم اضافه کنم که توی دنیای واقعی می‌تونستیم از `BigInt` استفاده کنیم ولی متاسفانه **کوئرا** قبول نمیکنه. خطای `Killed by a signal` یا `خطای نحوی` میده.
