### ISSUE TITLE
کمک 

### ISSUE THREAD

**Issue by amirhossien1** [HamidMolareza/QueraProblems#31]
سلام میشه سوال مدیریت دارو خانه و ناقل و مدیریت کارکنان را بزارید

**Comment by amirhossien1** [comment]
https://quera.org/college/3078/chapter/8773/lesson/30080/

https://quera.org/college/3078/chapter/8773/lesson/30080/

https://quera.org/college/3078/chapter/8773/lesson/103383/

**Comment by HamidMolareza** [comment]
این لینک‌ها برای دوره آموزشی هستن و دسترسی ندارم.

**Comment by amirhossien1** [comment]
در کارت گرافیک برای بالا بردن سرعت، پردازش بخش‌های مختلف به صورت موازی انجام می‌شود. این پردازش‌ها را می‌توان به شکل یک درخت نشان داد. در این سوال به پردازش نمونه‌ای از این درخت‌ها می‌پردازیم. درخت توابعی که در این سوال اجرا می‌شوند مانند شکل زیر است: هر یال جهت‌دار به این معناست که تابعی که یال از آن خارج شده باید قبل از تابعی که یال به آن وارد شده محاسبه شود. (می‌توان گفت تابعی که به آن یال وارد شده برای انجام محاسبتش نیاز به خروجی تابع اول دارد).

برای مثال قبل از این که تابع h1h1​ اجرا شود، باید توابع g1g1​ و g2g2​ هم اجرا شده باشد.

توابع در سه لیست f و g و h در فایل functions.py قرار دارند (برای مثال f[0] همان f1f1​​ است). هم‌چنین همه‌ی توابع آرگومانی به عنوان ورودی نمی‌گیرند؛ برای مثال برای صدا زدن تابع f1f1​ باید از عبارت f[0]() استفاده کنید.

شما باید با ۴ ترد به نام‌های '1' و '2' و '3' و '4' این توابع را به ترتیب زیر محاسبه کنید:

    ابتدا با ترد iiام، fifi​​ محاسبه شود.
    سپس با ترد iiام، gigi​ محاسبه شود.
    و در نهایت با ترد iiام، hihi​ محاسبه شود.

دقت کنید که محاسبات هر مرحله (طبقه‌ی درخت) باید به‌ صورت همزمان انجام شود. برای مثال f1f1​​ و f2f2​​ باید همزمان محاسبه شوند) حال از شما می‌خواهیم صدازدن توابع را به ترتیب ذکر شده با کمک تردها انجام دهید. شما باید کد خود را در تابعی به نام solve بنویسید و آن را ارسال کنید.

**Comment by HamidMolareza** [comment]
[python](https://github.com/HamidMolareza/QueraProblems/tree/master/Solutions/33040/python3)

**Comment by amirhossien1** [comment]
در این سوال از شما می‌خواهیم یک decorator بنویسید که مانند کلید واژه synchronized در جاوا عمل کند.

این دکوراتور باید به گونه‌ای باشه که اگر در بالای تابعی نوشته شد، ترد‌های مختلف نتوانند به صورت همزمان آن را صدا کنند؛ یعنی با استفاده از یک شی Lock باید کاری کند که در هر زمان فقط یک ترد درون تابع باشد و چند تردی که آن را صدا می‌کنند به ترتیب اجرا شوند.
