### ISSUE TITLE
کمک

### ISSUE THREAD

**Issue by amirhossien1** [HamidMolareza/QueraProblems#32]
در این سوال از شما می‌خواهیم یک decorator بنویسید که مانند کلید واژه synchronized در جاوا عمل کند.

این دکوراتور باید به گونه‌ای باشه که اگر در بالای تابعی نوشته شد، ترد‌های مختلف نتوانند به صورت همزمان آن را صدا کنند؛ یعنی با استفاده از یک شی Lock باید کاری کند که در هر زمان فقط یک ترد درون تابع باشد و چند تردی که آن را صدا می‌کنند به ترتیب اجرا شوند.

**Comment by HamidMolareza** [comment]
```
import threading


def synchronized(lock):
    def decorator(func):
        def wrapper(*args, **kwargs):
            with lock:
                return func(*args, **kwargs)

        return wrapper

    return decorator


global_lock = threading.Lock()


@synchronized(global_lock)
def synchronized_function():
    pass
```

این کد رو صرفا دستی چک کردم چون دسترسی به سیستم داوری نداشتم. ممکنه فقط لازم باشه تابع `synchronized` رو ارسال کنید.

پ.ن. فراموش نکنید این تمرین‌ها برای تقویت **مهارت حل مسئله** شما هستن که جزو کلیدی‌ترین مهارت‌های یک برنامه‌نویس هستش. برای همین حتما قبل از اینکه به دنبال جواب باشید سعی کنید به قدر کافی (حداقل چند ساعت) زمان بذارید.
